import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/provider/useTheme";

const jetbrains = localFont({
  src: "../../public/fonts/JetBrainsMono-Medium.ttf",
  variable: "--font-jetbrains",
});

const spacemono = localFont({
  src: "../../public/fonts/SpaceMono-Regular.ttf",
  variable: "--font-spacemono",
});

export const metadata: Metadata = {
  title: "SSK is here!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrains.variable} ${spacemono} antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
